// --------------------------------------------------
// Entity Actions
// --------------------------------------------------

// USER
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// SESSION
export const CREATE_SESSION_REQUEST = 'CREATE_SESSION_REQUEST';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE';

export const UPDATE_SESSION_REQUEST = 'UPDATE_SESSION_REQUEST';
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS';
export const UPDATE_SESSION_FAILURE = 'UPDATE_SESSION_FAILURE';

export const DELETE_SESSION_REQUEST = 'DELETE_SESSION_REQUEST';
export const DELETE_SESSION_SUCCESS = 'DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_FAILURE = 'DELETE_SESSION_FAILURE';

// ACTIVITY TYPE
export const ADD_ACTIVITY_TYPE = 'ADD_ACTIVITY_TYPE';
export const UPDATE_ACTIVITY_TYPE_REQUEST = 'UPDATE_ACTIVITY_TYPE_REQUEST';
export const UPDATE_ACTIVITY_TYPE_SUCCESS = 'UPDATE_ACTIVITY_TYPE_SUCCESS';
export const UPDATE_ACTIVITY_TYPE_FAILURE = 'UPDATE_ACTIVITY_TYPE_FAILURE';
export const REMOVE_ACTIVITY_TYPE = 'REMOVE_ACTIVITY_TYPE';

// ACTIVITY INSTANCE
export const CREATE_ACTIVITY_INSTANCE_REQUEST = 'CREATE_ACTIVITY_INSTANCE_REQUEST';
export const CREATE_ACTIVITY_INSTANCE_SUCCESS = 'CREATE_ACTIVITY_INSTANCE_SUCCESS';
export const CREATE_ACTIVITY_INSTANCE_FAILURE = 'CREATE_ACTIVITY_INSTANCE_FAILURE';

export const UPDATE_ACTIVITY_INSTANCE_REQUEST = 'UPDATE_ACTIVITY_INSTANCE_REQUEST';
export const UPDATE_ACTIVITY_INSTANCE_SUCCESS = 'UPDATE_ACTIVITY_INSTANCE_SUCCESS';
export const UPDATE_ACTIVITY_INSTANCE_FAILURE = 'UPDATE_ACTIVITY_INSTANCE_FAILURE';

export const DELETE_ACTIVITY_INSTANCE_REQUEST = 'DELETE_ACTIVITY_INSTANCE_REQUEST';
export const DELETE_ACTIVITY_INSTANCE_SUCCESS = 'DELETE_ACTIVITY_INSTANCE_SUCCESS';
export const DELETE_ACTIVITY_INSTANCE_FAILURE = 'DELETE_ACTIVITY_INSTANCE_FAILURE';

// CATEGORY
export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

// --------------------------------------------------
// Server Actions
// --------------------------------------------------

export const UPDATE_FROM_SERVER = 'UPDATE_FROM_SERVER';

// --------------------------------------------------
// App Actions
// --------------------------------------------------


export const CLOSE_ADD_ACTIVITY_MODAL = 'CLOSE_ADD_ACTIVITY_MODAL';
export const OPEN_ADD_ACTIVITY_MODAL = 'OPEN_ADD_ACTIVITY_MODAL';