// USER
const ADD_USER = 'ADD_USER';
const EDIT_USER = 'EDIT_USER';
const DELETE_USER = 'DELETE_USER';

// SESSION
const ADD_SESSION = 'ADD_SESSION';
const EDIT_SESSION = 'EDIT_SESSION';
const DELETE_SESSION = 'DELETE_SESSION';

// ACTIVITY
const ADD_ACTIVITY = 'ADD_ACTIVITY';
const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
const DELETE_ACTIVITY = 'DELETE_ACTIVITY';

// CATEGORY
const ADD_CATEGORY = 'ADD_CATEGORY';
const EDIT_CATEGORY = 'EDIT_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';


export {
  ADD_USER,
  EDIT_USER,
  DELETE_USER,
  ADD_SESSION,
  EDIT_SESSION,
  DELETE_SESSION,
  ADD_ACTIVITY,
  EDIT_ACTIVITY,
  DELETE_ACTIVITY,
  ADD_CATEGORY,
  EDIT_CATEGORY,
  DELETE_CATEGORY ,
}